// Generated by psc-bundle 0.7.4.0
var PS = { };
(function(exports) {
  /* global exports */
  "use strict";

  // module Prelude

  //- Functor --------------------------------------------------------------------

  exports.arrayMap = function (f) {
    return function (arr) {
      var l = arr.length;
      var result = new Array(l);
      for (var i = 0; i < l; i++) {
        result[i] = f(arr[i]);
      }
      return result;
    };
  };

  //- Bind -----------------------------------------------------------------------

  exports.arrayBind = function (arr) {
    return function (f) {
      var result = [];
      for (var i = 0, l = arr.length; i < l; i++) {
        Array.prototype.push.apply(result, f(arr[i]));
      }
      return result;
    };
  };

  //- Eq -------------------------------------------------------------------------

  exports.refEq = function (r1) {
    return function (r2) {
      return r1 === r2;
    };
  };
 
})(PS["Prelude"] = PS["Prelude"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.0
  "use strict";
  var $foreign = PS["Prelude"];
  var Semigroupoid = function (compose) {
      this.compose = compose;
  };
  var Category = function (__superclass_Prelude$dotSemigroupoid_0, id) {
      this["__superclass_Prelude.Semigroupoid_0"] = __superclass_Prelude$dotSemigroupoid_0;
      this.id = id;
  };
  var Functor = function (map) {
      this.map = map;
  };
  var Apply = function (__superclass_Prelude$dotFunctor_0, apply) {
      this["__superclass_Prelude.Functor_0"] = __superclass_Prelude$dotFunctor_0;
      this.apply = apply;
  };
  var Applicative = function (__superclass_Prelude$dotApply_0, pure) {
      this["__superclass_Prelude.Apply_0"] = __superclass_Prelude$dotApply_0;
      this.pure = pure;
  };
  var Bind = function (__superclass_Prelude$dotApply_0, bind) {
      this["__superclass_Prelude.Apply_0"] = __superclass_Prelude$dotApply_0;
      this.bind = bind;
  };
  var Monad = function (__superclass_Prelude$dotApplicative_0, __superclass_Prelude$dotBind_1) {
      this["__superclass_Prelude.Applicative_0"] = __superclass_Prelude$dotApplicative_0;
      this["__superclass_Prelude.Bind_1"] = __superclass_Prelude$dotBind_1;
  };
  var Semigroup = function (append) {
      this.append = append;
  };
  var Eq = function (eq) {
      this.eq = eq;
  };                                                                           
  var unit = {};                                                         
  var semigroupoidFn = new Semigroupoid(function (f) {
      return function (g) {
          return function (x) {
              return f(g(x));
          };
      };
  });                 
  var pure = function (dict) {
      return dict.pure;
  };
  var $$return = function (__dict_Applicative_2) {
      return pure(__dict_Applicative_2);
  };
  var otherwise = true;
  var map = function (dict) {
      return dict.map;
  };
  var $less$dollar$greater = function (__dict_Functor_5) {
      return map(__dict_Functor_5);
  };
  var $less$hash$greater = function (__dict_Functor_6) {
      return function (fa) {
          return function (f) {
              return $less$dollar$greater(__dict_Functor_6)(f)(fa);
          };
      };
  };
  var id = function (dict) {
      return dict.id;
  };
  var functorArray = new Functor($foreign.arrayMap);
  var flip = function (f) {
      return function (b) {
          return function (a) {
              return f(a)(b);
          };
      };
  }; 
  var eqString = new Eq($foreign.refEq);
  var eq = function (dict) {
      return dict.eq;
  };
  var $eq$eq = function (__dict_Eq_7) {
      return eq(__dict_Eq_7);
  };
  var $$const = function (a) {
      return function (_73) {
          return a;
      };
  };
  var $$void = function (__dict_Functor_12) {
      return function (fa) {
          return $less$dollar$greater(__dict_Functor_12)($$const(unit))(fa);
      };
  };
  var compose = function (dict) {
      return dict.compose;
  };
  var functorFn = new Functor(compose(semigroupoidFn));
  var $less$less$less = function (__dict_Semigroupoid_14) {
      return compose(__dict_Semigroupoid_14);
  };
  var $greater$greater$greater = function (__dict_Semigroupoid_15) {
      return flip(compose(__dict_Semigroupoid_15));
  };
  var categoryFn = new Category(function () {
      return semigroupoidFn;
  }, function (x) {
      return x;
  });
  var bind = function (dict) {
      return dict.bind;
  };
  var liftM1 = function (__dict_Monad_23) {
      return function (f) {
          return function (a) {
              return bind(__dict_Monad_23["__superclass_Prelude.Bind_1"]())(a)(function (_14) {
                  return $$return(__dict_Monad_23["__superclass_Prelude.Applicative_0"]())(f(_14));
              });
          };
      };
  };
  var $greater$greater$eq = function (__dict_Bind_24) {
      return bind(__dict_Bind_24);
  }; 
  var apply = function (dict) {
      return dict.apply;
  };
  var $less$times$greater = function (__dict_Apply_25) {
      return apply(__dict_Apply_25);
  };
  var liftA1 = function (__dict_Applicative_26) {
      return function (f) {
          return function (a) {
              return $less$times$greater(__dict_Applicative_26["__superclass_Prelude.Apply_0"]())(pure(__dict_Applicative_26)(f))(a);
          };
      };
  }; 
  var append = function (dict) {
      return dict.append;
  };
  var $plus$plus = function (__dict_Semigroup_27) {
      return append(__dict_Semigroup_27);
  };
  var $less$greater = function (__dict_Semigroup_28) {
      return append(__dict_Semigroup_28);
  };
  var ap = function (__dict_Monad_30) {
      return function (f) {
          return function (a) {
              return bind(__dict_Monad_30["__superclass_Prelude.Bind_1"]())(f)(function (_16) {
                  return bind(__dict_Monad_30["__superclass_Prelude.Bind_1"]())(a)(function (_15) {
                      return $$return(__dict_Monad_30["__superclass_Prelude.Applicative_0"]())(_16(_15));
                  });
              });
          };
      };
  };
  var monadArray = new Monad(function () {
      return applicativeArray;
  }, function () {
      return bindArray;
  });
  var bindArray = new Bind(function () {
      return applyArray;
  }, $foreign.arrayBind);
  var applyArray = new Apply(function () {
      return functorArray;
  }, ap(monadArray));
  var applicativeArray = new Applicative(function () {
      return applyArray;
  }, function (x) {
      return [ x ];
  });
  exports["Eq"] = Eq;
  exports["Semigroup"] = Semigroup;
  exports["Monad"] = Monad;
  exports["Bind"] = Bind;
  exports["Applicative"] = Applicative;
  exports["Apply"] = Apply;
  exports["Functor"] = Functor;
  exports["Category"] = Category;
  exports["Semigroupoid"] = Semigroupoid;
  exports["=="] = $eq$eq;
  exports["eq"] = eq;
  exports["++"] = $plus$plus;
  exports["<>"] = $less$greater;
  exports["append"] = append;
  exports["ap"] = ap;
  exports["liftM1"] = liftM1;
  exports["return"] = $$return;
  exports[">>="] = $greater$greater$eq;
  exports["bind"] = bind;
  exports["liftA1"] = liftA1;
  exports["pure"] = pure;
  exports["<*>"] = $less$times$greater;
  exports["apply"] = apply;
  exports["void"] = $$void;
  exports["<#>"] = $less$hash$greater;
  exports["<$>"] = $less$dollar$greater;
  exports["map"] = map;
  exports["id"] = id;
  exports[">>>"] = $greater$greater$greater;
  exports["<<<"] = $less$less$less;
  exports["compose"] = compose;
  exports["otherwise"] = otherwise;
  exports["const"] = $$const;
  exports["flip"] = flip;
  exports["unit"] = unit;
  exports["semigroupoidFn"] = semigroupoidFn;
  exports["categoryFn"] = categoryFn;
  exports["functorFn"] = functorFn;
  exports["functorArray"] = functorArray;
  exports["applyArray"] = applyArray;
  exports["applicativeArray"] = applicativeArray;
  exports["bindArray"] = bindArray;
  exports["monadArray"] = monadArray;
  exports["eqString"] = eqString;;
 
})(PS["Prelude"] = PS["Prelude"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.0
  "use strict";
  var Prelude = PS["Prelude"];     
  var Alt = function (__superclass_Prelude$dotFunctor_0, alt) {
      this["__superclass_Prelude.Functor_0"] = __superclass_Prelude$dotFunctor_0;
      this.alt = alt;
  };                                         
  var alt = function (dict) {
      return dict.alt;
  };
  exports["Alt"] = Alt;
  exports["alt"] = alt;;
 
})(PS["Control.Alt"] = PS["Control.Alt"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module Control.Monad.Eff

  exports.returnE = function (a) {
    return function () {
      return a;
    };
  };

  exports.bindE = function (a) {
    return function (f) {
      return function () {
        return f(a())();
      };
    };
  };

  exports.runPure = function (f) {
    return f();
  };
 
})(PS["Control.Monad.Eff"] = PS["Control.Monad.Eff"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.0
  "use strict";
  var $foreign = PS["Control.Monad.Eff"];
  var Prelude = PS["Prelude"];     
  var monadEff = new Prelude.Monad(function () {
      return applicativeEff;
  }, function () {
      return bindEff;
  });
  var bindEff = new Prelude.Bind(function () {
      return applyEff;
  }, $foreign.bindE);
  var applyEff = new Prelude.Apply(function () {
      return functorEff;
  }, Prelude.ap(monadEff));
  var applicativeEff = new Prelude.Applicative(function () {
      return applyEff;
  }, $foreign.returnE);
  var functorEff = new Prelude.Functor(Prelude.liftA1(applicativeEff));
  exports["functorEff"] = functorEff;
  exports["applyEff"] = applyEff;
  exports["applicativeEff"] = applicativeEff;
  exports["bindEff"] = bindEff;
  exports["monadEff"] = monadEff;
  exports["runPure"] = $foreign.runPure;;
 
})(PS["Control.Monad.Eff"] = PS["Control.Monad.Eff"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module Control.Monad.Eff.Unsafe

  exports.unsafeInterleaveEff = function (f) {
    return f;
  };
 
})(PS["Control.Monad.Eff.Unsafe"] = PS["Control.Monad.Eff.Unsafe"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.0
  "use strict";
  var $foreign = PS["Control.Monad.Eff.Unsafe"];
  var Prelude = PS["Prelude"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  exports["unsafeInterleaveEff"] = $foreign.unsafeInterleaveEff;;
 
})(PS["Control.Monad.Eff.Unsafe"] = PS["Control.Monad.Eff.Unsafe"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module Control.Monad.ST

  exports.newSTRef = function (val) {
    return function () {
      return { value: val };
    };
  };

  exports.readSTRef = function (ref) {
    return function () {
      return ref.value;
    };
  };

  exports.writeSTRef = function (ref) {
    return function (a) {
      return function () {
        /* jshint boss: true */
        return ref.value = a;
      };
    };
  };
 
})(PS["Control.Monad.ST"] = PS["Control.Monad.ST"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.0
  "use strict";
  var $foreign = PS["Control.Monad.ST"];
  var Prelude = PS["Prelude"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  exports["writeSTRef"] = $foreign.writeSTRef;
  exports["readSTRef"] = $foreign.readSTRef;
  exports["newSTRef"] = $foreign.newSTRef;;
 
})(PS["Control.Monad.ST"] = PS["Control.Monad.ST"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.0
  "use strict";
  var Prelude = PS["Prelude"];
  var Control_Alt = PS["Control.Alt"];     
  var Plus = function (__superclass_Control$dotAlt$dotAlt_0, empty) {
      this["__superclass_Control.Alt.Alt_0"] = __superclass_Control$dotAlt$dotAlt_0;
      this.empty = empty;
  };       
  var empty = function (dict) {
      return dict.empty;
  };
  exports["Plus"] = Plus;
  exports["empty"] = empty;;
 
})(PS["Control.Plus"] = PS["Control.Plus"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.0
  "use strict";
  var Prelude = PS["Prelude"];     
  var Monoid = function (__superclass_Prelude$dotSemigroup_0, mempty) {
      this["__superclass_Prelude.Semigroup_0"] = __superclass_Prelude$dotSemigroup_0;
      this.mempty = mempty;
  };       
  var mempty = function (dict) {
      return dict.mempty;
  };
  exports["Monoid"] = Monoid;
  exports["mempty"] = mempty;;
 
})(PS["Data.Monoid"] = PS["Data.Monoid"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.0
  "use strict";
  var Prelude = PS["Prelude"];
  var Control_Alt = PS["Control.Alt"];
  var Control_Alternative = PS["Control.Alternative"];
  var Control_Extend = PS["Control.Extend"];
  var Control_MonadPlus = PS["Control.MonadPlus"];
  var Control_Plus = PS["Control.Plus"];
  var Data_Functor_Invariant = PS["Data.Functor.Invariant"];
  var Data_Monoid = PS["Data.Monoid"];     
  var Nothing = (function () {
      function Nothing() {

      };
      Nothing.value = new Nothing();
      return Nothing;
  })();
  var Just = (function () {
      function Just(value0) {
          this.value0 = value0;
      };
      Just.create = function (value0) {
          return new Just(value0);
      };
      return Just;
  })();
  var maybe = function (b) {
      return function (f) {
          return function (_246) {
              if (_246 instanceof Nothing) {
                  return b;
              };
              if (_246 instanceof Just) {
                  return f(_246.value0);
              };
              throw new Error("Failed pattern match at Data.Maybe line 26, column 1 - line 27, column 1: " + [ b.constructor.name, f.constructor.name, _246.constructor.name ]);
          };
      };
  };                                                
  var functorMaybe = new Prelude.Functor(function (fn) {
      return function (_248) {
          if (_248 instanceof Just) {
              return new Just(fn(_248.value0));
          };
          return Nothing.value;
      };
  });
  var fromMaybe = function (a) {
      return maybe(a)(Prelude.id(Prelude.categoryFn));
  };
  exports["Nothing"] = Nothing;
  exports["Just"] = Just;
  exports["fromMaybe"] = fromMaybe;
  exports["maybe"] = maybe;
  exports["functorMaybe"] = functorMaybe;;
 
})(PS["Data.Maybe"] = PS["Data.Maybe"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.0
  "use strict";
  var Prelude = PS["Prelude"];
  var Control_Comonad = PS["Control.Comonad"];
  var Control_Extend = PS["Control.Extend"];
  var Data_Functor_Invariant = PS["Data.Functor.Invariant"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Monoid = PS["Data.Monoid"];     
  var First = function (x) {
      return x;
  };
  var semigroupFirst = new Prelude.Semigroup(function (_271) {
      return function (second) {
          if (_271 instanceof Data_Maybe.Just) {
              return _271;
          };
          return second;
      };
  });
  var runFirst = function (_260) {
      return _260;
  };
  var monoidFirst = new Data_Monoid.Monoid(function () {
      return semigroupFirst;
  }, Data_Maybe.Nothing.value);
  exports["First"] = First;
  exports["runFirst"] = runFirst;
  exports["semigroupFirst"] = semigroupFirst;
  exports["monoidFirst"] = monoidFirst;;
 
})(PS["Data.Maybe.First"] = PS["Data.Maybe.First"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.0
  "use strict";
  var $foreign = PS["Data.Foldable"];
  var Prelude = PS["Prelude"];
  var Control_Apply = PS["Control.Apply"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Maybe_First = PS["Data.Maybe.First"];
  var Data_Maybe_Last = PS["Data.Maybe.Last"];
  var Data_Monoid = PS["Data.Monoid"];
  var Data_Monoid_Additive = PS["Data.Monoid.Additive"];
  var Data_Monoid_Dual = PS["Data.Monoid.Dual"];
  var Data_Monoid_Disj = PS["Data.Monoid.Disj"];
  var Data_Monoid_Conj = PS["Data.Monoid.Conj"];
  var Data_Monoid_Multiplicative = PS["Data.Monoid.Multiplicative"];     
  var Foldable = function (foldMap, foldl, foldr) {
      this.foldMap = foldMap;
      this.foldl = foldl;
      this.foldr = foldr;
  };
  var foldr = function (dict) {
      return dict.foldr;
  };
  var foldl = function (dict) {
      return dict.foldl;
  }; 
  var foldMap = function (dict) {
      return dict.foldMap;
  };
  exports["Foldable"] = Foldable;
  exports["foldMap"] = foldMap;
  exports["foldl"] = foldl;
  exports["foldr"] = foldr;;
 
})(PS["Data.Foldable"] = PS["Data.Foldable"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.0
  "use strict";
  var Prelude = PS["Prelude"];
  var Control_Biapplicative = PS["Control.Biapplicative"];
  var Control_Biapply = PS["Control.Biapply"];
  var Control_Comonad = PS["Control.Comonad"];
  var Control_Extend = PS["Control.Extend"];
  var Control_Lazy = PS["Control.Lazy"];
  var Data_Bifoldable = PS["Data.Bifoldable"];
  var Data_Bifunctor = PS["Data.Bifunctor"];
  var Data_Bitraversable = PS["Data.Bitraversable"];
  var Data_Foldable = PS["Data.Foldable"];
  var Data_Functor_Invariant = PS["Data.Functor.Invariant"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Maybe_First = PS["Data.Maybe.First"];
  var Data_Monoid = PS["Data.Monoid"];
  var Data_Traversable = PS["Data.Traversable"];     
  var Tuple = (function () {
      function Tuple(value0, value1) {
          this.value0 = value0;
          this.value1 = value1;
      };
      Tuple.create = function (value0) {
          return function (value1) {
              return new Tuple(value0, value1);
          };
      };
      return Tuple;
  })();
  var snd = function (_470) {
      return _470.value1;
  };                                                                                                    
  var fst = function (_469) {
      return _469.value0;
  };
  exports["Tuple"] = Tuple;
  exports["snd"] = snd;
  exports["fst"] = fst;;
 
})(PS["Data.Tuple"] = PS["Data.Tuple"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.0
  "use strict";
  var Prelude = PS["Prelude"];
  var Control_Alt = PS["Control.Alt"];
  var Control_Extend = PS["Control.Extend"];
  var Data_Bifoldable = PS["Data.Bifoldable"];
  var Data_Bifunctor = PS["Data.Bifunctor"];
  var Data_Bitraversable = PS["Data.Bitraversable"];
  var Data_Foldable = PS["Data.Foldable"];
  var Data_Monoid = PS["Data.Monoid"];
  var Data_Traversable = PS["Data.Traversable"];     
  var Left = (function () {
      function Left(value0) {
          this.value0 = value0;
      };
      Left.create = function (value0) {
          return new Left(value0);
      };
      return Left;
  })();
  var Right = (function () {
      function Right(value0) {
          this.value0 = value0;
      };
      Right.create = function (value0) {
          return new Right(value0);
      };
      return Right;
  })();
  var functorEither = new Prelude.Functor(function (f) {
      return function (_359) {
          if (_359 instanceof Left) {
              return new Left(_359.value0);
          };
          if (_359 instanceof Right) {
              return new Right(f(_359.value0));
          };
          throw new Error("Failed pattern match at Data.Either line 52, column 1 - line 56, column 1: " + [ f.constructor.name, _359.constructor.name ]);
      };
  });
  var either = function (f) {
      return function (g) {
          return function (_358) {
              if (_358 instanceof Left) {
                  return f(_358.value0);
              };
              if (_358 instanceof Right) {
                  return g(_358.value0);
              };
              throw new Error("Failed pattern match at Data.Either line 28, column 1 - line 29, column 1: " + [ f.constructor.name, g.constructor.name, _358.constructor.name ]);
          };
      };
  }; 
  var applyEither = new Prelude.Apply(function () {
      return functorEither;
  }, function (_361) {
      return function (r) {
          if (_361 instanceof Left) {
              return new Left(_361.value0);
          };
          if (_361 instanceof Right) {
              return Prelude["<$>"](functorEither)(_361.value0)(r);
          };
          throw new Error("Failed pattern match at Data.Either line 92, column 1 - line 116, column 1: " + [ _361.constructor.name, r.constructor.name ]);
      };
  });
  var applicativeEither = new Prelude.Applicative(function () {
      return applyEither;
  }, Right.create);
  exports["Left"] = Left;
  exports["Right"] = Right;
  exports["either"] = either;
  exports["functorEither"] = functorEither;
  exports["applyEither"] = applyEither;
  exports["applicativeEither"] = applicativeEither;;
 
})(PS["Data.Either"] = PS["Data.Either"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.0
  "use strict";
  var Prelude = PS["Prelude"];
  var Control_Alt = PS["Control.Alt"];
  var Control_Alternative = PS["Control.Alternative"];
  var Control_Lazy = PS["Control.Lazy"];
  var Control_Monad_Rec_Class = PS["Control.Monad.Rec.Class"];
  var Control_Monad_Eff_Class = PS["Control.Monad.Eff.Class"];
  var Control_Monad_Trans = PS["Control.Monad.Trans"];
  var Control_MonadPlus = PS["Control.MonadPlus"];
  var Control_Plus = PS["Control.Plus"];
  var Data_Tuple = PS["Data.Tuple"];
  var Data_Either = PS["Data.Either"];     
  var StateT = function (x) {
      return x;
  };
  var runStateT = function (_554) {
      return _554;
  };
  var monadStateT = function (__dict_Monad_3) {
      return new Prelude.Monad(function () {
          return applicativeStateT(__dict_Monad_3);
      }, function () {
          return bindStateT(__dict_Monad_3);
      });
  };
  var functorStateT = function (__dict_Monad_10) {
      return new Prelude.Functor(Prelude.liftM1(monadStateT(__dict_Monad_10)));
  };
  var bindStateT = function (__dict_Monad_13) {
      return new Prelude.Bind(function () {
          return applyStateT(__dict_Monad_13);
      }, function (_555) {
          return function (f) {
              return function (s) {
                  return Prelude.bind(__dict_Monad_13["__superclass_Prelude.Bind_1"]())(_555(s))(function (_36) {
                      return runStateT(f(_36.value0))(_36.value1);
                  });
              };
          };
      });
  };
  var applyStateT = function (__dict_Monad_14) {
      return new Prelude.Apply(function () {
          return functorStateT(__dict_Monad_14);
      }, Prelude.ap(monadStateT(__dict_Monad_14)));
  };
  var applicativeStateT = function (__dict_Monad_15) {
      return new Prelude.Applicative(function () {
          return applyStateT(__dict_Monad_15);
      }, function (a) {
          return StateT(function (s) {
              return Prelude["return"](__dict_Monad_15["__superclass_Prelude.Applicative_0"]())(new Data_Tuple.Tuple(a, s));
          });
      });
  };
  exports["StateT"] = StateT;
  exports["runStateT"] = runStateT;
  exports["functorStateT"] = functorStateT;
  exports["applyStateT"] = applyStateT;
  exports["applicativeStateT"] = applicativeStateT;
  exports["bindStateT"] = bindStateT;
  exports["monadStateT"] = monadStateT;;
 
})(PS["Control.Monad.State.Trans"] = PS["Control.Monad.State.Trans"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.0
  "use strict";
  var Prelude = PS["Prelude"];
  var Control_Comonad = PS["Control.Comonad"];
  var Control_Extend = PS["Control.Extend"];
  var Data_Foldable = PS["Data.Foldable"];
  var Data_Functor_Invariant = PS["Data.Functor.Invariant"];
  var Data_Monoid = PS["Data.Monoid"];
  var Data_Traversable = PS["Data.Traversable"];     
  var Identity = function (x) {
      return x;
  };
  var runIdentity = function (_392) {
      return _392;
  };
  var functorIdentity = new Prelude.Functor(function (f) {
      return function (_415) {
          return f(_415);
      };
  });
  var applyIdentity = new Prelude.Apply(function () {
      return functorIdentity;
  }, function (_416) {
      return function (_417) {
          return _416(_417);
      };
  });
  var bindIdentity = new Prelude.Bind(function () {
      return applyIdentity;
  }, function (_418) {
      return function (f) {
          return f(_418);
      };
  });
  var applicativeIdentity = new Prelude.Applicative(function () {
      return applyIdentity;
  }, Identity);
  var monadIdentity = new Prelude.Monad(function () {
      return applicativeIdentity;
  }, function () {
      return bindIdentity;
  });
  exports["Identity"] = Identity;
  exports["runIdentity"] = runIdentity;
  exports["functorIdentity"] = functorIdentity;
  exports["applyIdentity"] = applyIdentity;
  exports["applicativeIdentity"] = applicativeIdentity;
  exports["bindIdentity"] = bindIdentity;
  exports["monadIdentity"] = monadIdentity;;
 
})(PS["Data.Identity"] = PS["Data.Identity"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.0
  "use strict";
  var Prelude = PS["Prelude"];
  var Control_Monad_State_Trans = PS["Control.Monad.State.Trans"];
  var Data_Identity = PS["Data.Identity"];
  var Data_Tuple = PS["Data.Tuple"];                   
  var runState = function (s) {
      return Prelude["<<<"](Prelude.semigroupoidFn)(Data_Identity.runIdentity)(Control_Monad_State_Trans.runStateT(s));
  };
  var execState = function (m) {
      return function (s) {
          return Data_Tuple.snd(runState(m)(s));
      };
  };
  exports["execState"] = execState;
  exports["runState"] = runState;;
 
})(PS["Control.Monad.State"] = PS["Control.Monad.State"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.0
  "use strict";
  var Prelude = PS["Prelude"];
  var Control_Monad_Trans = PS["Control.Monad.Trans"];
  var Control_Monad_State_Trans = PS["Control.Monad.State.Trans"];
  var Control_Monad_Error = PS["Control.Monad.Error"];
  var Control_Monad_Error_Trans = PS["Control.Monad.Error.Trans"];
  var Control_Monad_Maybe_Trans = PS["Control.Monad.Maybe.Trans"];
  var Control_Monad_Reader_Trans = PS["Control.Monad.Reader.Trans"];
  var Control_Monad_RWS_Trans = PS["Control.Monad.RWS.Trans"];
  var Control_Monad_Writer_Trans = PS["Control.Monad.Writer.Trans"];
  var Data_Monoid = PS["Data.Monoid"];
  var Data_Tuple = PS["Data.Tuple"];
  var Control_Monad_RWS = PS["Control.Monad.RWS"];     
  var MonadState = function (state) {
      this.state = state;
  };
  var state = function (dict) {
      return dict.state;
  };
  var monadStateStateT = function (__dict_Monad_7) {
      return new MonadState(function (f) {
          return Control_Monad_State_Trans.StateT(Prelude["<<<"](Prelude.semigroupoidFn)(Prelude["return"](__dict_Monad_7["__superclass_Prelude.Applicative_0"]()))(f));
      });
  };
  var modify = function (__dict_Monad_16) {
      return function (__dict_MonadState_17) {
          return function (f) {
              return state(__dict_MonadState_17)(function (s) {
                  return new Data_Tuple.Tuple(Prelude.unit, f(s));
              });
          };
      };
  };
  exports["MonadState"] = MonadState;
  exports["modify"] = modify;
  exports["state"] = state;
  exports["monadStateStateT"] = monadStateStateT;;
 
})(PS["Control.Monad.State.Class"] = PS["Control.Monad.State.Class"] || {});
(function(exports) {
  /* global exports, window */
  "use strict";

  // module DOM.HTML

  exports.window = function () {
    return window;
  };
 
})(PS["DOM.HTML"] = PS["DOM.HTML"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // jshint maxparams: 1
  exports.toForeign = function (value) {
    return value;
  };

  exports.unsafeFromForeign = function (value) {
    return value;
  };

  exports.typeOf = function (value) {
    return typeof value;
  };

  exports.tagOf = function (value) {
    return Object.prototype.toString.call(value).slice(8, -1);
  };
 
})(PS["Data.Foreign"] = PS["Data.Foreign"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module Data.Int

  exports.fromNumberImpl = function (just) {
    return function (nothing) {
      return function (n) {
        /* jshint bitwise: false */
        return (n | 0) === n ? just(n) : nothing;
      };
    };
  };
 
})(PS["Data.Int"] = PS["Data.Int"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module Data.Maybe.Unsafe

  exports.unsafeThrow = function (msg) {
    throw new Error(msg);
  };
 
})(PS["Data.Maybe.Unsafe"] = PS["Data.Maybe.Unsafe"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.0
  "use strict";
  var $foreign = PS["Data.Maybe.Unsafe"];
  var Prelude = PS["Prelude"];
  var Data_Maybe = PS["Data.Maybe"];     
  var fromJust = function (_309) {
      if (_309 instanceof Data_Maybe.Just) {
          return _309.value0;
      };
      if (_309 instanceof Data_Maybe.Nothing) {
          return $foreign.unsafeThrow("Data.Maybe.Unsafe.fromJust called on Nothing");
      };
      throw new Error("Failed pattern match at Data.Maybe.Unsafe line 10, column 1 - line 11, column 1: " + [ _309.constructor.name ]);
  };
  exports["fromJust"] = fromJust;;
 
})(PS["Data.Maybe.Unsafe"] = PS["Data.Maybe.Unsafe"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.0
  "use strict";
  var $foreign = PS["Data.Int"];
  var Prelude = PS["Prelude"];
  var Data_Int_Bits = PS["Data.Int.Bits"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Maybe_Unsafe = PS["Data.Maybe.Unsafe"];
  var $$Math = PS["Math"];                                                                   
  var fromNumber = $foreign.fromNumberImpl(Data_Maybe.Just.create)(Data_Maybe.Nothing.value);
  exports["fromNumber"] = fromNumber;;
 
})(PS["Data.Int"] = PS["Data.Int"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.0
  "use strict";
  var $foreign = PS["Data.Foreign"];
  var Prelude = PS["Prelude"];
  var Data_Either = PS["Data.Either"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Function = PS["Data.Function"];
  var Data_Int = PS["Data.Int"];
  var Data_String = PS["Data.String"];     
  var TypeMismatch = (function () {
      function TypeMismatch(value0, value1) {
          this.value0 = value0;
          this.value1 = value1;
      };
      TypeMismatch.create = function (value0) {
          return function (value1) {
              return new TypeMismatch(value0, value1);
          };
      };
      return TypeMismatch;
  })();
  var unsafeReadTagged = function (tag) {
      return function (value) {
          if (Prelude["=="](Prelude.eqString)($foreign.tagOf(value))(tag)) {
              return Prelude.pure(Data_Either.applicativeEither)($foreign.unsafeFromForeign(value));
          };
          return new Data_Either.Left(new TypeMismatch(tag, $foreign.tagOf(value)));
      };
  }; 
  var readString = unsafeReadTagged("String");
  var readNumber = unsafeReadTagged("Number");
  var readInt = function (value) {
      var error = Data_Either.Left.create(new TypeMismatch("Int", $foreign.tagOf(value)));
      var fromNumber = Prelude["<<<"](Prelude.semigroupoidFn)(Data_Maybe.maybe(error)(Prelude.pure(Data_Either.applicativeEither)))(Data_Int.fromNumber);
      return Data_Either.either(Prelude["const"](error))(fromNumber)(readNumber(value));
  };
  var readBoolean = unsafeReadTagged("Boolean");
  exports["TypeMismatch"] = TypeMismatch;
  exports["readInt"] = readInt;
  exports["readNumber"] = readNumber;
  exports["readBoolean"] = readBoolean;
  exports["readString"] = readString;
  exports["unsafeReadTagged"] = unsafeReadTagged;
  exports["typeOf"] = $foreign.typeOf;
  exports["toForeign"] = $foreign.toForeign;;
 
})(PS["Data.Foreign"] = PS["Data.Foreign"] || {});
(function(exports) {
  "use strict";

  // module Unsafe.Coerce

  exports.unsafeCoerce = function(x) { return x; }
 
})(PS["Unsafe.Coerce"] = PS["Unsafe.Coerce"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.0
  "use strict";
  var $foreign = PS["Unsafe.Coerce"];
  exports["unsafeCoerce"] = $foreign.unsafeCoerce;;
 
})(PS["Unsafe.Coerce"] = PS["Unsafe.Coerce"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.0
  "use strict";
  var $foreign = PS["DOM.HTML.Types"];
  var Prelude = PS["Prelude"];
  var Data_Either = PS["Data.Either"];
  var Data_Foreign = PS["Data.Foreign"];
  var Data_Foreign_Class = PS["Data.Foreign.Class"];
  var DOM_Event_Types = PS["DOM.Event.Types"];
  var DOM_Node_Types = PS["DOM.Node.Types"];
  var Unsafe_Coerce = PS["Unsafe.Coerce"];                  
  var htmlElementToElement = Unsafe_Coerce.unsafeCoerce;
  exports["htmlElementToElement"] = htmlElementToElement;;
 
})(PS["DOM.HTML.Types"] = PS["DOM.HTML.Types"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.0
  "use strict";
  var $foreign = PS["DOM.HTML"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var DOM = PS["DOM"];
  var DOM_HTML_Types = PS["DOM.HTML.Types"];
  exports["window"] = $foreign.window;;
 
})(PS["DOM.HTML"] = PS["DOM.HTML"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module DOM.HTML.Document

  exports.body = function (doc) {
    return function () {
      return doc.body;
    };
  };
 
})(PS["DOM.HTML.Document"] = PS["DOM.HTML.Document"] || {});
(function(exports) {
  /* global exports */
  "use strict";          

  exports.nullable = function(a, r, f) {
      return a == null ? r : f(a);
  }; 
 
})(PS["Data.Nullable"] = PS["Data.Nullable"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.0
  "use strict";
  var $foreign = PS["Data.Nullable"];
  var Prelude = PS["Prelude"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Function = PS["Data.Function"];                              
  var toMaybe = function (n) {
      return $foreign.nullable(n, Data_Maybe.Nothing.value, Data_Maybe.Just.create);
  };
  exports["toMaybe"] = toMaybe;;
 
})(PS["Data.Nullable"] = PS["Data.Nullable"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.0
  "use strict";
  var $foreign = PS["DOM.HTML.Document"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Data_Nullable = PS["Data.Nullable"];
  var DOM = PS["DOM"];
  var DOM_HTML_Types = PS["DOM.HTML.Types"];
  exports["body"] = $foreign.body;;
 
})(PS["DOM.HTML.Document"] = PS["DOM.HTML.Document"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module DOM.HTML.Window

  exports.document = function (window) {
    return function () {
      return window.document;
    };
  };
 
})(PS["DOM.HTML.Window"] = PS["DOM.HTML.Window"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.0
  "use strict";
  var $foreign = PS["DOM.HTML.Window"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var DOM = PS["DOM"];
  var DOM_HTML_Types = PS["DOM.HTML.Types"];
  exports["document"] = $foreign.document;;
 
})(PS["DOM.HTML.Window"] = PS["DOM.HTML.Window"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module Data.Array.ST

  exports.runSTArray = function (f) {
    return f;
  };

  exports.emptySTArray = function () {
    return [];
  };

  exports.pushAllSTArray = function (xs) {
    return function (as) {
      return function () {
        return xs.push.apply(xs, as);
      };
    };
  };
 
})(PS["Data.Array.ST"] = PS["Data.Array.ST"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.0
  "use strict";
  var $foreign = PS["Data.Array.ST"];
  var Prelude = PS["Prelude"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Control_Monad_ST = PS["Control.Monad.ST"];
  var Data_Maybe = PS["Data.Maybe"];
  var pushSTArray = function (arr) {
      return function (a) {
          return $foreign.pushAllSTArray(arr)([ a ]);
      };
  };
  exports["pushSTArray"] = pushSTArray;
  exports["emptySTArray"] = $foreign.emptySTArray;
  exports["runSTArray"] = $foreign.runSTArray;;
 
})(PS["Data.Array.ST"] = PS["Data.Array.ST"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.0
  "use strict";
  var Prelude = PS["Prelude"];     
  var Contravariant = function (cmap) {
      this.cmap = cmap;
  };
  var cmap = function (dict) {
      return dict.cmap;
  };
  exports["Contravariant"] = Contravariant;
  exports["cmap"] = cmap;;
 
})(PS["Data.Functor.Contravariant"] = PS["Data.Functor.Contravariant"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.0
  "use strict";
  var Prelude = PS["Prelude"];
  var Data_Bifoldable = PS["Data.Bifoldable"];
  var Data_Foldable = PS["Data.Foldable"];
  var Data_Functor_Contravariant = PS["Data.Functor.Contravariant"];
  var Data_Functor_Invariant = PS["Data.Functor.Invariant"];
  var Data_Monoid = PS["Data.Monoid"];
  var Data_Traversable = PS["Data.Traversable"];     
  var Const = function (x) {
      return x;
  };
  var getConst = function (_329) {
      return _329;
  };
  var functorConst = new Prelude.Functor(function (_339) {
      return function (_340) {
          return _340;
      };
  });
  var contravariantConst = new Data_Functor_Contravariant.Contravariant(function (_346) {
      return function (_347) {
          return _347;
      };
  });
  var applyConst = function (__dict_Semigroup_10) {
      return new Prelude.Apply(function () {
          return functorConst;
      }, function (_341) {
          return function (_342) {
              return Prelude["<>"](__dict_Semigroup_10)(_341)(_342);
          };
      });
  };
  var applicativeConst = function (__dict_Monoid_11) {
      return new Prelude.Applicative(function () {
          return applyConst(__dict_Monoid_11["__superclass_Prelude.Semigroup_0"]());
      }, function (_345) {
          return Data_Monoid.mempty(__dict_Monoid_11);
      });
  };
  exports["Const"] = Const;
  exports["getConst"] = getConst;
  exports["functorConst"] = functorConst;
  exports["applyConst"] = applyConst;
  exports["applicativeConst"] = applicativeConst;
  exports["contravariantConst"] = contravariantConst;;
 
})(PS["Data.Const"] = PS["Data.Const"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module Data.Foreign.Index

  // jshint maxparams: 4
  exports.unsafeReadPropImpl = function (f, s, key, value) {
    return value == null ? f : s(value[key]);
  };
 
})(PS["Data.Foreign.Index"] = PS["Data.Foreign.Index"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.0
  "use strict";
  var $foreign = PS["Data.Foreign.Index"];
  var Prelude = PS["Prelude"];
  var Data_Either = PS["Data.Either"];
  var Data_Foreign = PS["Data.Foreign"];
  var Data_Function = PS["Data.Function"];
  var Data_Int = PS["Data.Int"];
  var unsafeReadProp = function (k) {
      return function (value) {
          return $foreign.unsafeReadPropImpl(new Data_Either.Left(new Data_Foreign.TypeMismatch("object", Data_Foreign.typeOf(value))), Prelude.pure(Data_Either.applicativeEither), k, value);
      };
  };
  var prop = unsafeReadProp;
  exports["prop"] = prop;;
 
})(PS["Data.Foreign.Index"] = PS["Data.Foreign.Index"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.0
  "use strict";
  var Prelude = PS["Prelude"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Maybe_First = PS["Data.Maybe.First"];
  var Data_Const = PS["Data.Const"];
  var Data_Either = PS["Data.Either"];
  var Data_Monoid = PS["Data.Monoid"];
  var Data_Functor_Contravariant = PS["Data.Functor.Contravariant"];
  var Data_Foreign = PS["Data.Foreign"];
  var Data_Foreign_Index = PS["Data.Foreign.Index"];
  var Data_Foreign_Keys = PS["Data.Foreign.Keys"];
  var getMap = function (__dict_Monoid_0) {
      return function (f) {
          return function (g) {
              return Prelude["<<<"](Prelude.semigroupoidFn)(Data_Const.getConst)(g(Data_Const.contravariantConst)(Data_Const.applicativeConst(__dict_Monoid_0))(Prelude["<<<"](Prelude.semigroupoidFn)(Data_Const.Const)(f)));
          };
      };
  };
  var get = function (g) {
      return Prelude["<<<"](Prelude.semigroupoidFn)(Data_Maybe_First.runFirst)(getMap(Data_Maybe_First.monoidFirst)(Prelude["<<<"](Prelude.semigroupoidFn)(Data_Maybe_First.First)(Data_Maybe.Just.create))(function (__dict_Contravariant_1) {
          return function (__dict_Applicative_2) {
              return g(__dict_Contravariant_1)(__dict_Applicative_2);
          };
      }));
  };
  var coerce = function (__dict_Contravariant_3) {
      return function (__dict_Functor_4) {
          var absurd = function (__copy_a) {
              var a = __copy_a;
              tco: while (true) {
                  var __tco_a = a;
                  a = __tco_a;
                  continue tco;
              };
          };
          return Prelude["<<<"](Prelude.semigroupoidFn)(Prelude.map(__dict_Functor_4)(absurd))(Data_Functor_Contravariant.cmap(__dict_Contravariant_3)(absurd));
      };
  };
  var getter = function (f) {
      return function (__dict_Contravariant_5) {
          return function (__dict_Applicative_6) {
              return function (g) {
                  return function (s) {
                      var _1424 = f(s);
                      if (_1424 instanceof Data_Either.Left) {
                          return coerce(__dict_Contravariant_5)((__dict_Applicative_6["__superclass_Prelude.Apply_0"]())["__superclass_Prelude.Functor_0"]())(Prelude.pure(__dict_Applicative_6)(Prelude.unit));
                      };
                      if (_1424 instanceof Data_Either.Right) {
                          return coerce(__dict_Contravariant_5)((__dict_Applicative_6["__superclass_Prelude.Apply_0"]())["__superclass_Prelude.Functor_0"]())(g(_1424.value0));
                      };
                      throw new Error("Failed pattern match at Data.Foreign.Lens line 54, column 1 - line 55, column 1: " + [ _1424.constructor.name ]);
                  };
              };
          };
      };
  };
  var $$int = function (__dict_Contravariant_9) {
      return function (__dict_Applicative_10) {
          return getter(Data_Foreign.readInt)(__dict_Contravariant_9)(__dict_Applicative_10);
      };
  };
  var prop = function (p) {
      return function (__dict_Contravariant_17) {
          return function (__dict_Applicative_18) {
              return getter(Data_Foreign_Index.prop(p))(__dict_Contravariant_17)(__dict_Applicative_18);
          };
      };
  };
  var string = function (__dict_Contravariant_19) {
      return function (__dict_Applicative_20) {
          return getter(Data_Foreign.readString)(__dict_Contravariant_19)(__dict_Applicative_20);
      };
  };
  var $$boolean = function (__dict_Contravariant_23) {
      return function (__dict_Applicative_24) {
          return getter(Data_Foreign.readBoolean)(__dict_Contravariant_23)(__dict_Applicative_24);
      };
  };
  exports["prop"] = prop;
  exports["int"] = $$int;
  exports["boolean"] = $$boolean;
  exports["string"] = string;
  exports["getMap"] = getMap;
  exports["get"] = get;
  exports["getter"] = getter;;
 
})(PS["Data.Foreign.Lens"] = PS["Data.Foreign.Lens"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.0
  "use strict";
  var Prelude = PS["Prelude"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Tuple = PS["Data.Tuple"];
  var Data_Array_ST = PS["Data.Array.ST"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Control_Monad_ST = PS["Control.Monad.ST"];     
  var Unfoldable = function (unfoldr) {
      this.unfoldr = unfoldr;
  };
  var unfoldr = function (dict) {
      return dict.unfoldr;
  };
  var unfoldableArray = new Unfoldable(function (f) {
      return function (b) {
          return Control_Monad_Eff.runPure(Data_Array_ST.runSTArray(function __do() {
              var _54 = Data_Array_ST.emptySTArray();
              var _53 = Control_Monad_ST.newSTRef(b)();
              (function () {
                  while (!(function __do() {
                      var _52 = Control_Monad_ST.readSTRef(_53)();
                      return (function () {
                          var _2192 = f(_52);
                          if (_2192 instanceof Data_Maybe.Nothing) {
                              return Prelude["return"](Control_Monad_Eff.applicativeEff)(true);
                          };
                          if (_2192 instanceof Data_Maybe.Just) {
                              return function __do() {
                                  Data_Array_ST.pushSTArray(_54)(_2192.value0.value0)();
                                  Control_Monad_ST.writeSTRef(_53)(_2192.value0.value1)();
                                  return Prelude["return"](Control_Monad_Eff.applicativeEff)(false)();
                              };
                          };
                          throw new Error("Failed pattern match at Data.Unfoldable line 28, column 1 - line 40, column 16: " + [ _2192.constructor.name ]);
                      })()();
                  })()) {

                  };
                  return {};
              })();
              return Prelude["return"](Control_Monad_Eff.applicativeEff)(_54)();
          }));
      };
  });
  exports["Unfoldable"] = Unfoldable;
  exports["unfoldr"] = unfoldr;
  exports["unfoldableArray"] = unfoldableArray;;
 
})(PS["Data.Unfoldable"] = PS["Data.Unfoldable"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.0
  "use strict";
  var Prelude = PS["Prelude"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Tuple = PS["Data.Tuple"];
  var Data_Monoid = PS["Data.Monoid"];
  var Data_Foldable = PS["Data.Foldable"];
  var Data_Unfoldable = PS["Data.Unfoldable"];
  var Data_Traversable = PS["Data.Traversable"];
  var Control_Alt = PS["Control.Alt"];
  var Control_Lazy = PS["Control.Lazy"];
  var Control_Plus = PS["Control.Plus"];
  var Control_Alternative = PS["Control.Alternative"];
  var Control_MonadPlus = PS["Control.MonadPlus"];     
  var Nil = (function () {
      function Nil() {

      };
      Nil.value = new Nil();
      return Nil;
  })();
  var Cons = (function () {
      function Cons(value0, value1) {
          this.value0 = value0;
          this.value1 = value1;
      };
      Cons.create = function (value0) {
          return function (value1) {
              return new Cons(value0, value1);
          };
      };
      return Cons;
  })();
  var $colon = Cons.create;
  var zipWith = function (f) {
      return function (_704) {
          return function (_705) {
              if (_704 instanceof Nil) {
                  return Nil.value;
              };
              if (_705 instanceof Nil) {
                  return Nil.value;
              };
              if (_704 instanceof Cons && _705 instanceof Cons) {
                  return new Cons(f(_704.value0)(_705.value0), zipWith(f)(_704.value1)(_705.value1));
              };
              throw new Error("Failed pattern match: " + [ f.constructor.name, _704.constructor.name, _705.constructor.name ]);
          };
      };
  };
  var zip = zipWith(Data_Tuple.Tuple.create);
  var updateAt = function (_690) {
      return function (x) {
          return function (_691) {
              if (_690 === 0 && _691 instanceof Cons) {
                  return new Data_Maybe.Just(new Cons(x, _691.value1));
              };
              if (_691 instanceof Cons) {
                  return Prelude["<$>"](Data_Maybe.functorMaybe)(Cons.create(_691.value0))(updateAt(_690 - 1)(x)(_691.value1));
              };
              return Data_Maybe.Nothing.value;
          };
      };
  }; 
  var uncons = function (_683) {
      if (_683 instanceof Nil) {
          return Data_Maybe.Nothing.value;
      };
      if (_683 instanceof Cons) {
          return new Data_Maybe.Just({
              head: _683.value0, 
              tail: _683.value1
          });
      };
      throw new Error("Failed pattern match at Data.List line 264, column 1 - line 265, column 1: " + [ _683.constructor.name ]);
  };
  var tail = function (_681) {
      if (_681 instanceof Nil) {
          return Data_Maybe.Nothing.value;
      };
      if (_681 instanceof Cons) {
          return new Data_Maybe.Just(_681.value1);
      };
      throw new Error("Failed pattern match at Data.List line 248, column 1 - line 249, column 1: " + [ _681.constructor.name ]);
  };
  var singleton = function (a) {
      return new Cons(a, Nil.value);
  };
  var semigroupList = new Prelude.Semigroup(function (_727) {
      return function (ys) {
          if (_727 instanceof Nil) {
              return ys;
          };
          if (_727 instanceof Cons) {
              return new Cons(_727.value0, Prelude["<>"](semigroupList)(_727.value1)(ys));
          };
          throw new Error("Failed pattern match: " + [ _727.constructor.name, ys.constructor.name ]);
      };
  });
  var reverse = (function () {
      var go = function (__copy_acc) {
          return function (__copy__708) {
              var acc = __copy_acc;
              var _708 = __copy__708;
              tco: while (true) {
                  var acc_1 = acc;
                  if (_708 instanceof Nil) {
                      return acc_1;
                  };
                  if (_708 instanceof Cons) {
                      var __tco_acc = new Cons(_708.value0, acc);
                      var __tco__708 = _708.value1;
                      acc = __tco_acc;
                      _708 = __tco__708;
                      continue tco;
                  };
                  throw new Error("Failed pattern match at Data.List line 362, column 1 - line 363, column 1: " + [ acc.constructor.name, _708.constructor.name ]);
              };
          };
      };
      return go(Nil.value);
  })();
  var range = function (start) {
      return function (end) {
          if (start === end) {
              return singleton(start);
          };
          if (Prelude.otherwise) {
              var go = function (__copy_s) {
                  return function (__copy_e) {
                      return function (__copy_step) {
                          return function (__copy_rest) {
                              var s = __copy_s;
                              var e = __copy_e;
                              var step = __copy_step;
                              var rest = __copy_rest;
                              tco: while (true) {
                                  if (s === e) {
                                      return new Cons(s, rest);
                                  };
                                  if (Prelude.otherwise) {
                                      var __tco_s = s + step | 0;
                                      var __tco_e = e;
                                      var __tco_step = step;
                                      var __tco_rest = new Cons(s, rest);
                                      s = __tco_s;
                                      e = __tco_e;
                                      step = __tco_step;
                                      rest = __tco_rest;
                                      continue tco;
                                  };
                                  throw new Error("Failed pattern match at Data.List line 137, column 1 - line 138, column 1: " + [ s.constructor.name, e.constructor.name, step.constructor.name, rest.constructor.name ]);
                              };
                          };
                      };
                  };
              };
              return go(end)(start)((function () {
                  var _2467 = start > end;
                  if (_2467) {
                      return 1;
                  };
                  if (!_2467) {
                      return -1;
                  };
                  throw new Error("Failed pattern match at Data.List line 137, column 1 - line 138, column 1: " + [ _2467.constructor.name ]);
              })())(Nil.value);
          };
          throw new Error("Failed pattern match at Data.List line 137, column 1 - line 138, column 1: " + [ start.constructor.name, end.constructor.name ]);
      };
  };
  var index = function (__copy__684) {
      return function (__copy__685) {
          var _684 = __copy__684;
          var _685 = __copy__685;
          tco: while (true) {
              if (_684 instanceof Nil) {
                  return Data_Maybe.Nothing.value;
              };
              if (_684 instanceof Cons && _685 === 0) {
                  return new Data_Maybe.Just(_684.value0);
              };
              if (_684 instanceof Cons) {
                  var __tco__684 = _684.value1;
                  var __tco__685 = _685 - 1;
                  _684 = __tco__684;
                  _685 = __tco__685;
                  continue tco;
              };
              throw new Error("Failed pattern match: " + [ _684.constructor.name, _685.constructor.name ]);
          };
      };
  };
  var $bang$bang = index;
  var head = function (_679) {
      if (_679 instanceof Nil) {
          return Data_Maybe.Nothing.value;
      };
      if (_679 instanceof Cons) {
          return new Data_Maybe.Just(_679.value0);
      };
      throw new Error("Failed pattern match at Data.List line 233, column 1 - line 234, column 1: " + [ _679.constructor.name ]);
  };
  var functorList = new Prelude.Functor(function (f) {
      return function (_728) {
          if (_728 instanceof Nil) {
              return Nil.value;
          };
          if (_728 instanceof Cons) {
              return new Cons(f(_728.value0), Prelude["<$>"](functorList)(f)(_728.value1));
          };
          throw new Error("Failed pattern match: " + [ f.constructor.name, _728.constructor.name ]);
      };
  });
  var fromList = function (__dict_Unfoldable_15) {
      return Data_Unfoldable.unfoldr(__dict_Unfoldable_15)(function (xs) {
          return Prelude["<$>"](Data_Maybe.functorMaybe)(function (rec) {
              return new Data_Tuple.Tuple(rec.head, rec.tail);
          })(uncons(xs));
      });
  };
  var foldableList = new Data_Foldable.Foldable(function (__dict_Monoid_16) {
      return function (f) {
          return Data_Foldable.foldl(foldableList)(function (acc) {
              return Prelude["<<<"](Prelude.semigroupoidFn)(Prelude.append(__dict_Monoid_16["__superclass_Prelude.Semigroup_0"]())(acc))(f);
          })(Data_Monoid.mempty(__dict_Monoid_16));
      };
  }, (function () {
      var go = function (__copy_o) {
          return function (__copy_b) {
              return function (__copy__730) {
                  var o = __copy_o;
                  var b = __copy_b;
                  var _730 = __copy__730;
                  tco: while (true) {
                      var b_1 = b;
                      if (_730 instanceof Nil) {
                          return b_1;
                      };
                      if (_730 instanceof Cons) {
                          var __tco_o = o;
                          var __tco_b = o(b)(_730.value0);
                          var __tco__730 = _730.value1;
                          o = __tco_o;
                          b = __tco_b;
                          _730 = __tco__730;
                          continue tco;
                      };
                      throw new Error("Failed pattern match: " + [ o.constructor.name, b.constructor.name, _730.constructor.name ]);
                  };
              };
          };
      };
      return go;
  })(), function (o) {
      return function (b) {
          return function (_729) {
              if (_729 instanceof Nil) {
                  return b;
              };
              if (_729 instanceof Cons) {
                  return o(_729.value0)(Data_Foldable.foldr(foldableList)(o)(b)(_729.value1));
              };
              throw new Error("Failed pattern match: " + [ o.constructor.name, b.constructor.name, _729.constructor.name ]);
          };
      };
  });
  var length = Data_Foldable.foldl(foldableList)(function (acc) {
      return function (_674) {
          return acc + 1 | 0;
      };
  })(0);
  var filter = function (p) {
      var go = function (__copy_acc) {
          return function (__copy__709) {
              var acc = __copy_acc;
              var _709 = __copy__709;
              tco: while (true) {
                  var acc_1 = acc;
                  if (_709 instanceof Nil) {
                      return reverse(acc_1);
                  };
                  if (_709 instanceof Cons) {
                      if (p(_709.value0)) {
                          var __tco_acc = new Cons(_709.value0, acc);
                          var __tco__709 = _709.value1;
                          acc = __tco_acc;
                          _709 = __tco__709;
                          continue tco;
                      };
                      if (Prelude.otherwise) {
                          var __tco_acc = acc;
                          var __tco__709 = _709.value1;
                          acc = __tco_acc;
                          _709 = __tco__709;
                          continue tco;
                      };
                  };
                  throw new Error("Failed pattern match at Data.List line 385, column 1 - line 386, column 1: " + [ acc.constructor.name, _709.constructor.name ]);
              };
          };
      };
      return go(Nil.value);
  };
  var deleteAt = function (_688) {
      return function (_689) {
          if (_688 === 0 && _689 instanceof Cons) {
              return new Data_Maybe.Just(_689.value1);
          };
          if (_689 instanceof Cons) {
              return Prelude["<$>"](Data_Maybe.functorMaybe)(Cons.create(_689.value0))(deleteAt(_688 - 1)(_689.value1));
          };
          return Data_Maybe.Nothing.value;
      };
  };
  var altList = new Control_Alt.Alt(function () {
      return functorList;
  }, Prelude.append(semigroupList));
  var plusList = new Control_Plus.Plus(function () {
      return altList;
  }, Nil.value);
  exports["Nil"] = Nil;
  exports["Cons"] = Cons;
  exports["zip"] = zip;
  exports["zipWith"] = zipWith;
  exports["filter"] = filter;
  exports["reverse"] = reverse;
  exports["updateAt"] = updateAt;
  exports["deleteAt"] = deleteAt;
  exports["index"] = index;
  exports["!!"] = $bang$bang;
  exports["uncons"] = uncons;
  exports["tail"] = tail;
  exports["head"] = head;
  exports[":"] = $colon;
  exports["length"] = length;
  exports["range"] = range;
  exports["singleton"] = singleton;
  exports["fromList"] = fromList;
  exports["semigroupList"] = semigroupList;
  exports["functorList"] = functorList;
  exports["foldableList"] = foldableList;
  exports["altList"] = altList;
  exports["plusList"] = plusList;;
 
})(PS["Data.List"] = PS["Data.List"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.0
  "use strict";
  var Prelude = PS["Prelude"];     
  var Profunctor = function (dimap) {
      this.dimap = dimap;
  };
  var profunctorFn = new Profunctor(function (a2b) {
      return function (c2d) {
          return function (b2c) {
              return Prelude[">>>"](Prelude.semigroupoidFn)(a2b)(Prelude[">>>"](Prelude.semigroupoidFn)(b2c)(c2d));
          };
      };
  });
  var dimap = function (dict) {
      return dict.dimap;
  };
  var rmap = function (__dict_Profunctor_1) {
      return function (b2c) {
          return dimap(__dict_Profunctor_1)(Prelude.id(Prelude.categoryFn))(b2c);
      };
  };
  exports["Profunctor"] = Profunctor;
  exports["rmap"] = rmap;
  exports["dimap"] = dimap;
  exports["profunctorFn"] = profunctorFn;;
 
})(PS["Data.Profunctor"] = PS["Data.Profunctor"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.0
  "use strict";
  var Data_Functor_Contravariant = PS["Data.Functor.Contravariant"];
  var Data_Identity = PS["Data.Identity"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Profunctor = PS["Data.Profunctor"];
  var Optic_Internal_Setter = PS["Optic.Internal.Setter"];
  var Optic_Types = PS["Optic.Types"];
  var Prelude = PS["Prelude"];
  var set = function (stab) {
      return function (b) {
          return Prelude["<<<"](Prelude.semigroupoidFn)(Data_Identity.runIdentity)(stab(Prelude["<<<"](Prelude.semigroupoidFn)(Data_Identity.Identity)(Prelude["const"](b))));
      };
  };
  var $dot$tilde = set;
  var over = function (__dict_Profunctor_3) {
      return function (pstab) {
          return function (pab) {
              return Prelude["<<<"](Prelude.semigroupoidFn)(Data_Identity.runIdentity)(pstab(Data_Profunctor.rmap(__dict_Profunctor_3)(Data_Identity.Identity)(pab)));
          };
      };
  };
  var $plus$plus$tilde = function (__dict_Semigroup_7) {
      return function (staa) {
          return function (a) {
              return over(Data_Profunctor.profunctorFn)(staa)(Prelude.flip(Prelude["++"](__dict_Semigroup_7))(a));
          };
      };
  };
  exports["set"] = set;
  exports["over"] = over;
  exports["++~"] = $plus$plus$tilde;
  exports[".~"] = $dot$tilde;;
 
})(PS["Optic.Setter"] = PS["Optic.Setter"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.0
  "use strict";
  var Optic_Getter = PS["Optic.Getter"];
  var Optic_Lens = PS["Optic.Lens"];
  var Optic_Prism = PS["Optic.Prism"];
  var Optic_Setter = PS["Optic.Setter"];
  var Optic_Types = PS["Optic.Types"];
  var Prelude = PS["Prelude"];     
  var $dot$dot = function (__dict_Semigroupoid_0) {
      return Prelude["<<<"](__dict_Semigroupoid_0);
  };
  exports[".."] = $dot$dot;;
 
})(PS["Optic.Core"] = PS["Optic.Core"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.0
  "use strict";
  var Prelude = PS["Prelude"];
  var Control_Monad_State = PS["Control.Monad.State"];     
  var $hash$tilde = function (s) {
      return function (sa) {
          return Control_Monad_State.execState(sa)(s);
      };
  };
  exports["#~"] = $hash$tilde;;
 
})(PS["Optic.Monad"] = PS["Optic.Monad"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.0
  "use strict";
  var Prelude = PS["Prelude"];
  var Data_Identity = PS["Data.Identity"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_List = PS["Data.List"];
  var Data_Map = PS["Data.Map"];
  var Data_Set = PS["Data.Set"];
  var Data_StrMap = PS["Data.StrMap"];     
  var IndexKey = {};
  var IndexValue = {};           
  var indexValueList = IndexValue;
  var indexKeyList = IndexKey;
  exports["IndexValue"] = IndexValue;
  exports["IndexKey"] = IndexKey;
  exports["indexKeyList"] = indexKeyList;
  exports["indexValueList"] = indexValueList;;
 
})(PS["Optic.Index.Class"] = PS["Optic.Index.Class"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.0
  "use strict";
  var Prelude = PS["Prelude"];
  var Data_Identity = PS["Data.Identity"];
  var Data_Maybe = PS["Data.Maybe"];
  var Optic_Index_Class = PS["Optic.Index.Class"];
  var Optic_Index_Types = PS["Optic.Index.Types"];
  var Data_Array = PS["Data.Array"];
  var Data_List = PS["Data.List"];
  var Data_Set = PS["Data.Set"];
  var Data_Map = PS["Data.Map"];
  var Data_StrMap = PS["Data.StrMap"];     
  var Index = function (__superclass_Optic$dotIndex$dotClass$dotIndexKey_0, __superclass_Optic$dotIndex$dotClass$dotIndexValue_1, ix) {
      this["__superclass_Optic.Index.Class.IndexKey_0"] = __superclass_Optic$dotIndex$dotClass$dotIndexKey_0;
      this["__superclass_Optic.Index.Class.IndexValue_1"] = __superclass_Optic$dotIndex$dotClass$dotIndexValue_1;
      this.ix = ix;
  };
  var ix = function (dict) {
      return dict.ix;
  };
  var indexList = new Index(function () {
      return Optic_Index_Class.indexKeyList;
  }, function () {
      return Optic_Index_Class.indexValueList;
  }, function (n) {
      return function (__dict_Applicative_6) {
          return function (a2fa) {
              return function (as) {
                  return Data_Maybe.maybe(Prelude.pure(__dict_Applicative_6)(as))(function (a) {
                      return Prelude["<$>"]((__dict_Applicative_6["__superclass_Prelude.Apply_0"]())["__superclass_Prelude.Functor_0"]())(function (a$prime) {
                          return Data_Maybe.fromMaybe(as)(Data_List.updateAt(n)(a$prime)(as));
                      })(a2fa(a));
                  })(Data_List["!!"](as)(n));
              };
          };
      };
  });
  exports["Index"] = Index;
  exports["ix"] = ix;
  exports["indexList"] = indexList;;
 
})(PS["Optic.Index"] = PS["Optic.Index"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.0
  "use strict";
  var Prelude = PS["Prelude"];
  var Control_Monad_State_Class = PS["Control.Monad.State.Class"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Profunctor = PS["Data.Profunctor"];
  var Optic_Setter = PS["Optic.Setter"];
  var Optic_Types = PS["Optic.Types"];
  var $dot$eq = function (__dict_Monad_11) {
      return function (__dict_MonadState_12) {
          return function (ssab) {
              return function (b) {
                  return Control_Monad_State_Class.modify(__dict_Monad_11)(__dict_MonadState_12)(Optic_Setter[".~"](ssab)(b));
              };
          };
      };
  };
  var $plus$plus$eq = function (__dict_Monad_19) {
      return function (__dict_MonadState_20) {
          return function (__dict_Semigroup_21) {
              return function (ssab) {
                  return function (b) {
                      return Control_Monad_State_Class.modify(__dict_Monad_19)(__dict_MonadState_20)(Optic_Setter["++~"](__dict_Semigroup_21)(ssab)(b));
                  };
              };
          };
      };
  };
  exports["++="] = $plus$plus$eq;
  exports[".="] = $dot$eq;;
 
})(PS["Optic.Monad.Setter"] = PS["Optic.Monad.Setter"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module React

  exports.getProps = function(ctx) {
      return function() {
          return ctx.props;
      };
  };

  exports.getChildren = function(ctx) {
    return function() {
      return ctx.props.children;
    };
  };

  exports.writeState = function(ctx) {
      return function(state) {
          return function() {
              ctx.replaceState({
                  state: state
              });
              return function() {
                  return state;
              }
          };
      };
  };

  exports.readState = function(ctx) {
      return function() {
          return ctx.state.state;
      };
  };

  exports.createClass = function(ss) {
      var result = {};
      for (var s in ss) {
          if (ss.hasOwnProperty(s)) {
            if (s === "displayName") {
              result[s] = ss[s];
            }
            else if (s === "componentWillReceiveProps") {
              result[s] = (function(impl) {
                  return function(nextProps) {
                      return impl(this)(nextProps)();
                  }
              })(ss[s]);
            }
            else if (s === "shouldComponentUpdate") {
              result[s] = (function(impl) {
                  return function(nextProps, nextState) {
                      return impl(this)(nextProps)(nextState.state)();
                  }
              })(ss[s]);
            }
            else if (s === "componentWillUpdate") {
              result[s] = (function(impl) {
                  return function(nextProps, nextState) {
                      return impl(this)(nextProps)(nextState.state)();
                  }
              })(ss[s]);
            }
            else if (s === "componentDidUpdate") {
              result[s] = (function(impl) {
                  return function(prevProps, prevState) {
                      return impl(this)(prevProps)(prevState.state)();
                  }
              })(ss[s]);
            }
            else {
              result[s] = (function(impl) {
                  return function() {
                      return impl(this)();
                  }
              })(ss[s]);
            }
          }
      }
      result.getInitialState = function() {
          return {
              state: ss.getInitialState(this)()
          };
      };
      return React.createClass(result);
  };

  exports.handle = function(f) {
      return function(e) {
          return f(e)();
      };
  };

  exports.createFactory = function(clazz) {
    return React.createFactory(clazz);
  };

  exports.render = function(element) {
    return function(container) {
      return function() {
        return React.render(element, container);
      }
    };
  };                                            
 
})(PS["React"] = PS["React"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.0
  "use strict";
  var $foreign = PS["React"];
  var Prelude = PS["Prelude"];
  var DOM = PS["DOM"];
  var DOM_Node_Types = PS["DOM.Node.Types"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var spec = function (st) {
      return function (renderFn) {
          return {
              render: renderFn, 
              displayName: "", 
              getInitialState: function (_650) {
                  return Prelude.pure(Control_Monad_Eff.applicativeEff)(st);
              }, 
              componentWillMount: function (_651) {
                  return Prelude["return"](Control_Monad_Eff.applicativeEff)(Prelude.unit);
              }, 
              componentDidMount: function (_652) {
                  return Prelude["return"](Control_Monad_Eff.applicativeEff)(Prelude.unit);
              }, 
              componentWillReceiveProps: function (_654) {
                  return function (_653) {
                      return Prelude["return"](Control_Monad_Eff.applicativeEff)(Prelude.unit);
                  };
              }, 
              shouldComponentUpdate: function (_657) {
                  return function (_656) {
                      return function (_655) {
                          return Prelude["return"](Control_Monad_Eff.applicativeEff)(true);
                      };
                  };
              }, 
              componentWillUpdate: function (_660) {
                  return function (_659) {
                      return function (_658) {
                          return Prelude["return"](Control_Monad_Eff.applicativeEff)(Prelude.unit);
                      };
                  };
              }, 
              componentDidUpdate: function (_663) {
                  return function (_662) {
                      return function (_661) {
                          return Prelude["return"](Control_Monad_Eff.applicativeEff)(Prelude.unit);
                      };
                  };
              }, 
              componentWillUnmount: function (_664) {
                  return Prelude["return"](Control_Monad_Eff.applicativeEff)(Prelude.unit);
              }
          };
      };
  };
  exports["spec"] = spec;
  exports["render"] = $foreign.render;
  exports["createFactory"] = $foreign.createFactory;
  exports["createClass"] = $foreign.createClass;
  exports["handle"] = $foreign.handle;
  exports["writeState"] = $foreign.writeState;
  exports["readState"] = $foreign.readState;
  exports["getChildren"] = $foreign.getChildren;
  exports["getProps"] = $foreign.getProps;;
 
})(PS["React"] = PS["React"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.0
  "use strict";
  var React = PS["React"];
  var Prelude = PS["Prelude"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Control_Monad_Eff_Class = PS["Control.Monad.Eff.Class"];     
  var GetState = (function () {
      function GetState(value0) {
          this.value0 = value0;
      };
      GetState.create = function (value0) {
          return new GetState(value0);
      };
      return GetState;
  })();
  var SetState = (function () {
      function SetState(value0, value1) {
          this.value0 = value0;
          this.value1 = value1;
      };
      SetState.create = function (value0) {
          return function (value1) {
              return new SetState(value0, value1);
          };
      };
      return SetState;
  })();
  var Wait = (function () {
      function Wait(value0) {
          this.value0 = value0;
      };
      Wait.create = function (value0) {
          return new Wait(value0);
      };
      return Wait;
  })();
  var Pure = (function () {
      function Pure(value0) {
          this.value0 = value0;
      };
      Pure.create = function (value0) {
          return new Pure(value0);
      };
      return Pure;
  })();
  var Impure = (function () {
      function Impure(value0) {
          this.value0 = value0;
      };
      Impure.create = function (value0) {
          return new Impure(value0);
      };
      return Impure;
  })();
  var setState = function (s) {
      return Impure.create(new SetState(s, new Pure(Prelude.unit)));
  };
  var runAction = function ($$this) {
      var go = function (_666) {
          if (_666 instanceof Pure) {
              return Prelude["return"](Control_Monad_Eff.applicativeEff)(Prelude.unit);
          };
          if (_666 instanceof Impure && _666.value0 instanceof GetState) {
              return Prelude["void"](Control_Monad_Eff.functorEff)(function __do() {
                  var _58 = React.readState($$this)();
                  return go(_666.value0.value0(_58))();
              });
          };
          if (_666 instanceof Impure && _666.value0 instanceof SetState) {
              return Prelude["void"](Control_Monad_Eff.functorEff)(function __do() {
                  React.writeState($$this)(_666.value0.value0)();
                  return go(_666.value0.value1)();
              });
          };
          if (_666 instanceof Impure && _666.value0 instanceof Wait) {
              return _666.value0.value0(go);
          };
          throw new Error("Failed pattern match at Thermite.Action line 37, column 1 - line 41, column 1: " + [ _666.constructor.name ]);
      };
      return go;
  };
  var getState = Impure.create(new GetState(Pure.create));
  var functorActionF = new Prelude.Functor(function (f) {
      return function (_665) {
          if (_665 instanceof GetState) {
              return new GetState(Prelude["<<<"](Prelude.semigroupoidFn)(f)(_665.value0));
          };
          if (_665 instanceof SetState) {
              return new SetState(_665.value0, f(_665.value1));
          };
          if (_665 instanceof Wait) {
              return new Wait(function (k) {
                  return _665.value0(Prelude["<<<"](Prelude.semigroupoidFn)(k)(f));
              });
          };
          throw new Error("Failed pattern match at Thermite.Action line 24, column 1 - line 34, column 1: " + [ f.constructor.name, _665.constructor.name ]);
      };
  });
  var functorAction = new Prelude.Functor(function (f) {
      return function (_667) {
          if (_667 instanceof Pure) {
              return new Pure(f(_667.value0));
          };
          if (_667 instanceof Impure) {
              return new Impure(Prelude["<$>"](functorActionF)(Prelude["<$>"](functorAction)(f))(_667.value0));
          };
          throw new Error("Failed pattern match: " + [ f.constructor.name, _667.constructor.name ]);
      };
  });
  var monadAction = new Prelude.Monad(function () {
      return applicativeAction;
  }, function () {
      return bindAction;
  });
  var bindAction = new Prelude.Bind(function () {
      return applyAction;
  }, function (_668) {
      return function (f) {
          if (_668 instanceof Pure) {
              return f(_668.value0);
          };
          if (_668 instanceof Impure) {
              return Impure.create(Prelude["<#>"](functorActionF)(_668.value0)(function (a) {
                  return Prelude[">>="](bindAction)(a)(f);
              }));
          };
          throw new Error("Failed pattern match: " + [ _668.constructor.name, f.constructor.name ]);
      };
  });
  var applyAction = new Prelude.Apply(function () {
      return functorAction;
  }, Prelude.ap(monadAction));
  var applicativeAction = new Prelude.Applicative(function () {
      return applyAction;
  }, Pure.create);
  var modifyState = function (f) {
      return Prelude.bind(bindAction)(getState)(function (_59) {
          return setState(f(_59));
      });
  };
  exports["modifyState"] = modifyState;
  exports["setState"] = setState;
  exports["getState"] = getState;
  exports["runAction"] = runAction;
  exports["functorAction"] = functorAction;
  exports["applyAction"] = applyAction;
  exports["applicativeAction"] = applicativeAction;
  exports["bindAction"] = bindAction;
  exports["monadAction"] = monadAction;;
 
})(PS["Thermite.Action"] = PS["Thermite.Action"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.0
  "use strict";
  var React = PS["React"];
  var Prelude = PS["Prelude"];
  var DOM = PS["DOM"];
  var DOM_Node_Types = PS["DOM.Node.Types"];
  var Data_Maybe = PS["Data.Maybe"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Control_Monad_Eff_Unsafe = PS["Control.Monad.Eff.Unsafe"];
  var Thermite_Action = PS["Thermite.Action"];
  var Unsafe_Coerce = PS["Unsafe.Coerce"];
  var simpleSpec = function (initialState) {
      return function (performAction) {
          return function (render) {
              return {
                  initialState: initialState, 
                  performAction: performAction, 
                  render: render, 
                  componentWillMount: Data_Maybe.Nothing.value, 
                  displayName: Data_Maybe.Nothing.value
              };
          };
      };
  };
  var displayName = function (name) {
      return function (_850) {
          var _3423 = {};
          for (var _3424 in _850) {
              if (_850.hasOwnProperty(_3424)) {
                  _3423[_3424] = _850[_3424];
              };
          };
          _3423.displayName = new Data_Maybe.Just(name);
          return _3423;
      };
  };
  var createClass = function (_851) {
      var displayName_ = Data_Maybe.fromMaybe("")(_851.displayName);
      var dispatch = function ($$this) {
          return function (action) {
              return function __do() {
                  var _69 = React.getProps($$this)();
                  return Thermite_Action.runAction($$this)(Unsafe_Coerce.unsafeCoerce(_851.performAction(_69)(action)))();
              };
          };
      };
      var render = function ($$this) {
          return Prelude["<*>"](Control_Monad_Eff.applyEff)(Prelude["<*>"](Control_Monad_Eff.applyEff)(Prelude["<$>"](Control_Monad_Eff.functorEff)(_851.render(dispatch($$this)))(React.readState($$this)))(React.getProps($$this)))(React.getChildren($$this));
      };
      var componentWillMount_ = function (ctx) {
          return Data_Maybe.maybe(Prelude["return"](Control_Monad_Eff.applicativeEff)(Prelude.unit))(Prelude["<<<"](Prelude.semigroupoidFn)(Control_Monad_Eff_Unsafe.unsafeInterleaveEff)(dispatch(ctx)))(_851.componentWillMount);
      };
      return React.createClass((function () {
          var _3427 = {};
          for (var _3428 in React.spec(_851.initialState)(render)) {
              if ((React.spec(_851.initialState)(render)).hasOwnProperty(_3428)) {
                  _3427[_3428] = (React.spec(_851.initialState)(render))[_3428];
              };
          };
          _3427.displayName = displayName_;
          _3427.componentWillMount = componentWillMount_;
          return _3427;
      })());
  };
  var componentWillMount = function (action) {
      return function (_849) {
          var _3431 = {};
          for (var _3432 in _849) {
              if (_849.hasOwnProperty(_3432)) {
                  _3431[_3432] = _849[_3432];
              };
          };
          _3431.componentWillMount = new Data_Maybe.Just(action);
          return _3431;
      };
  };
  exports["displayName"] = displayName;
  exports["createClass"] = createClass;
  exports["componentWillMount"] = componentWillMount;
  exports["simpleSpec"] = simpleSpec;;
 
})(PS["Thermite"] = PS["Thermite"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module React.DOM

  function mkProps(props) {
      var result = {};

      for (var i = 0, len = props.length; i < len; i++) {
          var prop = props[i];

          for (var key in prop) {
              if (prop.hasOwnProperty(key)) {
                  result[key] = prop[key];
              }
          }
      }

      return result;
  };

  exports.mkDOM = function(tagName) {
      return function(props) {
          return function(children) {
              return React.createElement(tagName, props.length > 0 ? mkProps(props) : null, children);
          }
      }
  };

  exports.text = function(text) {
      return text;
  };
 
})(PS["React.DOM"] = PS["React.DOM"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module React.DOM.Props

  exports.unsafeMkProps = function(key) {
      return function(value) {
          var result = {};
          result[key] = value;
          return result;
      };
  };
 
})(PS["React.DOM.Props"] = PS["React.DOM.Props"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.0
  "use strict";
  var $foreign = PS["React.DOM.Props"];
  var Prelude = PS["Prelude"];
  var React = PS["React"];                    
  var value = $foreign.unsafeMkProps("value");  
  var title = $foreign.unsafeMkProps("title");  
  var placeholder = $foreign.unsafeMkProps("placeholder");
  var onKeyUp = function (f) {
      return $foreign.unsafeMkProps("onKeyUp")(React.handle(f));
  };
  var onClick = function (f) {
      return $foreign.unsafeMkProps("onClick")(React.handle(f));
  };
  var onChange = function (f) {
      return $foreign.unsafeMkProps("onChange")(React.handle(f));
  };                                              
  var className = $foreign.unsafeMkProps("className");
  var checked = $foreign.unsafeMkProps("checked");
  var _type = $foreign.unsafeMkProps("type");
  exports["onClick"] = onClick;
  exports["onChange"] = onChange;
  exports["onKeyUp"] = onKeyUp;
  exports["value"] = value;
  exports["_type"] = _type;
  exports["title"] = title;
  exports["placeholder"] = placeholder;
  exports["className"] = className;
  exports["checked"] = checked;;
 
})(PS["React.DOM.Props"] = PS["React.DOM.Props"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.0
  "use strict";
  var $foreign = PS["React.DOM"];
  var Prelude = PS["Prelude"];
  var React = PS["React"];
  var React_DOM_Props = PS["React.DOM.Props"];
  var tr = $foreign.mkDOM("tr");
  var tr$prime = tr([  ]);    
  var thead = $foreign.mkDOM("thead");
  var thead$prime = thead([  ]);
  var th = $foreign.mkDOM("th");      
  var td = $foreign.mkDOM("td");
  var td$prime = td([  ]);
  var tbody = $foreign.mkDOM("tbody");
  var tbody$prime = tbody([  ]);
  var table = $foreign.mkDOM("table");
  var input = $foreign.mkDOM("input");
  var h1 = $foreign.mkDOM("h1");
  var h1$prime = h1([  ]);
  var div = $foreign.mkDOM("div");
  var button = $foreign.mkDOM("button");
  var a = $foreign.mkDOM("a");
  exports["tr'"] = tr$prime;
  exports["tr"] = tr;
  exports["thead'"] = thead$prime;
  exports["thead"] = thead;
  exports["th"] = th;
  exports["td'"] = td$prime;
  exports["td"] = td;
  exports["tbody'"] = tbody$prime;
  exports["tbody"] = tbody;
  exports["table"] = table;
  exports["input"] = input;
  exports["h1'"] = h1$prime;
  exports["h1"] = h1;
  exports["div"] = div;
  exports["button"] = button;
  exports["a"] = a;
  exports["text"] = $foreign.text;;
 
})(PS["React.DOM"] = PS["React.DOM"] || {});
(function(exports) {
  // Generated by psc version 0.7.4.0
  "use strict";
  var Optic_Setter = PS["Optic.Setter"];
  var Prelude = PS["Prelude"];
  var Data_Tuple = PS["Data.Tuple"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Maybe_Unsafe = PS["Data.Maybe.Unsafe"];
  var Data_Nullable = PS["Data.Nullable"];
  var Data_Foreign = PS["Data.Foreign"];
  var Data_Foreign_Lens = PS["Data.Foreign.Lens"];
  var Data_List = PS["Data.List"];
  var Control_Plus = PS["Control.Plus"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Optic_Core = PS["Optic.Core"];
  var Optic_Monad = PS["Optic.Monad"];
  var Optic_Index = PS["Optic.Index"];
  var Optic_Monad_Setter = PS["Optic.Monad.Setter"];
  var Thermite = PS["Thermite"];
  var Thermite_Action = PS["Thermite.Action"];
  var React = PS["React"];
  var React_DOM = PS["React.DOM"];
  var React_DOM_Props = PS["React.DOM.Props"];
  var DOM = PS["DOM"];
  var DOM_HTML = PS["DOM.HTML"];
  var DOM_HTML_Document = PS["DOM.HTML.Document"];
  var DOM_HTML_Types = PS["DOM.HTML.Types"];
  var DOM_HTML_Window = PS["DOM.HTML.Window"];
  var DOM_Node_Types = PS["DOM.Node.Types"];
  var Data_Unfoldable = PS["Data.Unfoldable"];
  var Control_Monad_State_Trans = PS["Control.Monad.State.Trans"];
  var Data_Identity = PS["Data.Identity"];
  var Control_Monad_State_Class = PS["Control.Monad.State.Class"];
  var Data_Profunctor = PS["Data.Profunctor"];     
  var Item = (function () {
      function Item(value0, value1) {
          this.value0 = value0;
          this.value1 = value1;
      };
      Item.create = function (value0) {
          return function (value1) {
              return new Item(value0, value1);
          };
      };
      return Item;
  })();
  var All = (function () {
      function All() {

      };
      All.value = new All();
      return All;
  })();
  var Active = (function () {
      function Active() {

      };
      Active.value = new Active();
      return Active;
  })();
  var Completed = (function () {
      function Completed() {

      };
      Completed.value = new Completed();
      return Completed;
  })();
  var State = (function () {
      function State(value0) {
          this.value0 = value0;
      };
      State.create = function (value0) {
          return new State(value0);
      };
      return State;
  })();
  var NewItem = (function () {
      function NewItem(value0) {
          this.value0 = value0;
      };
      NewItem.create = function (value0) {
          return new NewItem(value0);
      };
      return NewItem;
  })();
  var RemoveItem = (function () {
      function RemoveItem(value0) {
          this.value0 = value0;
      };
      RemoveItem.create = function (value0) {
          return new RemoveItem(value0);
      };
      return RemoveItem;
  })();
  var SetEditText = (function () {
      function SetEditText(value0) {
          this.value0 = value0;
      };
      SetEditText.create = function (value0) {
          return new SetEditText(value0);
      };
      return SetEditText;
  })();
  var SetCompleted = (function () {
      function SetCompleted(value0, value1) {
          this.value0 = value0;
          this.value1 = value1;
      };
      SetCompleted.create = function (value0) {
          return function (value1) {
              return new SetCompleted(value0, value1);
          };
      };
      return SetCompleted;
  })();
  var SetFilter = (function () {
      function SetFilter(value0) {
          this.value0 = value0;
      };
      SetFilter.create = function (value0) {
          return new SetFilter(value0);
      };
      return SetFilter;
  })();
  var DoNothing = (function () {
      function DoNothing() {

      };
      DoNothing.value = new DoNothing();
      return DoNothing;
  })();
  var showFilter = function (_5) {
      if (_5 instanceof All) {
          return "All";
      };
      if (_5 instanceof Active) {
          return "Active";
      };
      if (_5 instanceof Completed) {
          return "Completed";
      };
      throw new Error("Failed pattern match at Main line 65, column 1 - line 66, column 1: " + [ _5.constructor.name ]);
  };
  var items = function (__dict_Functor_0) {
      return function (f) {
          return function (st) {
              return Prelude["<#>"](__dict_Functor_0)(f(st.items))(function (i) {
                  var _19 = {};
                  for (var _20 in st) {
                      if (st.hasOwnProperty(_20)) {
                          _19[_20] = st[_20];
                      };
                  };
                  _19.items = i;
                  return _19;
              });
          };
      };
  };
  var itemBoolean = function (__dict_Functor_1) {
      return function (f) {
          return function (_7) {
              return Prelude["<$>"](__dict_Functor_1)(Item.create(_7.value0))(f(_7.value1));
          };
      };
  };
  var initialState = new State({
      items: Control_Plus.empty(Data_List.plusList), 
      editText: "", 
      filter: All.value
  });
  var getValue = Prelude["<<<"](Prelude.semigroupoidFn)(Data_Maybe.fromMaybe(""))(Prelude["<<<"](Prelude.semigroupoidFn)(Data_Foreign_Lens.get(function (__dict_Contravariant_2) {
      return function (__dict_Applicative_3) {
          return Prelude["<<<"](Prelude.semigroupoidFn)(Data_Foreign_Lens.prop("target")(__dict_Contravariant_2)(__dict_Applicative_3))(Prelude["<<<"](Prelude.semigroupoidFn)(Data_Foreign_Lens.prop("value")(__dict_Contravariant_2)(__dict_Applicative_3))(Data_Foreign_Lens.string(__dict_Contravariant_2)(__dict_Applicative_3)));
      };
  }))(Data_Foreign.toForeign));
  var handleChangeEvent = function (e) {
      return new SetEditText(getValue(e));
  };
  var getKeyCode = Prelude["<<<"](Prelude.semigroupoidFn)(Data_Maybe.fromMaybe(0))(Prelude["<<<"](Prelude.semigroupoidFn)(Data_Foreign_Lens.get(function (__dict_Contravariant_4) {
      return function (__dict_Applicative_5) {
          return Prelude["<<<"](Prelude.semigroupoidFn)(Data_Foreign_Lens.prop("keyCode")(__dict_Contravariant_4)(__dict_Applicative_5))(Data_Foreign_Lens["int"](__dict_Contravariant_4)(__dict_Applicative_5));
      };
  }))(Data_Foreign.toForeign));
  var handleKeyPress = function (e) {
      var _25 = getKeyCode(e);
      if (_25 === 13) {
          return NewItem.create(getValue(e));
      };
      if (_25 === 27) {
          return new SetEditText("");
      };
      return DoNothing.value;
  };
  var getChecked = Prelude["<<<"](Prelude.semigroupoidFn)(Data_Maybe.fromMaybe(false))(Prelude["<<<"](Prelude.semigroupoidFn)(Data_Foreign_Lens.get(function (__dict_Contravariant_6) {
      return function (__dict_Applicative_7) {
          return Prelude["<<<"](Prelude.semigroupoidFn)(Data_Foreign_Lens.prop("target")(__dict_Contravariant_6)(__dict_Applicative_7))(Prelude["<<<"](Prelude.semigroupoidFn)(Data_Foreign_Lens.prop("checked")(__dict_Contravariant_6)(__dict_Applicative_7))(Data_Foreign_Lens["boolean"](__dict_Contravariant_6)(__dict_Applicative_7)));
      };
  }))(Data_Foreign.toForeign));
  var handleCheckEvent = function (index) {
      return function (e) {
          return new SetCompleted(index, getChecked(e));
      };
  };
  var filter_ = function (__dict_Functor_8) {
      return function (f) {
          return function (st) {
              return Prelude["<#>"](__dict_Functor_8)(f(st.filter))(function (i) {
                  var _26 = {};
                  for (var _27 in st) {
                      if (st.hasOwnProperty(_27)) {
                          _26[_27] = st[_27];
                      };
                  };
                  _26.filter = i;
                  return _26;
              });
          };
      };
  };
  var eqFilter = new Prelude.Eq(function (_14) {
      return function (_15) {
          if (_14 instanceof All && _15 instanceof All) {
              return true;
          };
          if (_14 instanceof Active && _15 instanceof Active) {
              return true;
          };
          if (_14 instanceof Completed && _15 instanceof Completed) {
              return true;
          };
          return false;
      };
  });
  var editText = function (__dict_Functor_9) {
      return function (f) {
          return function (st) {
              return Prelude["<#>"](__dict_Functor_9)(f(st.editText))(function (i) {
                  var _30 = {};
                  for (var _31 in st) {
                      if (st.hasOwnProperty(_31)) {
                          _30[_31] = st[_31];
                      };
                  };
                  _30.editText = i;
                  return _30;
              });
          };
      };
  };
  var applyFilter = function (_8) {
      return function (_9) {
          if (_8 instanceof All) {
              return true;
          };
          if (_8 instanceof Active) {
              return !_9.value1;
          };
          if (_8 instanceof Completed) {
              return _9.value1;
          };
          throw new Error("Failed pattern match at Main line 115, column 1 - line 116, column 1: " + [ _8.constructor.name, _9.constructor.name ]);
      };
  };
  var render = function (send) {
      return function (_10) {
          return function (_11) {
              return function (_12) {
                  var title = React_DOM["h1'"]([ React_DOM.text("todos") ]);
                  var newItem = React_DOM["tr'"]([ React_DOM["td'"]([  ]), React_DOM["td'"]([ React_DOM.input([ React_DOM_Props.className("form-control"), React_DOM_Props.placeholder("Create a new task"), React_DOM_Props.value(_10.value0.editText), React_DOM_Props.onKeyUp(Prelude["<<<"](Prelude.semigroupoidFn)(send)(handleKeyPress)), React_DOM_Props.onChange(Prelude["<<<"](Prelude.semigroupoidFn)(send)(handleChangeEvent)) ])([  ]) ]), React_DOM["td'"]([  ]) ]);
                  var item = function (_16) {
                      return Prelude["<<<"](Prelude.semigroupoidFn)(React_DOM["tr'"])(Prelude.map(Prelude.functorArray)(Prelude["<<<"](Prelude.semigroupoidFn)(React_DOM["td'"])(Prelude.pure(Prelude.applicativeArray))))([ React_DOM.input([ React_DOM_Props._type("checkbox"), React_DOM_Props.className("checkbox"), React_DOM_Props.checked((function () {
                          if (_16.value0.value1) {
                              return "checked";
                          };
                          if (!_16.value0.value1) {
                              return "";
                          };
                          throw new Error("Failed pattern match at Main line 120, column 1 - line 121, column 1: " + [ _16.value0.value1.constructor.name ]);
                      })()), React_DOM_Props.title("Mark as completed"), React_DOM_Props.onChange(Prelude["<<<"](Prelude.semigroupoidFn)(send)(handleCheckEvent(_16.value1))) ])([  ]), React_DOM.text(_16.value0.value0), React_DOM.a([ React_DOM_Props.className("btn btn-danger pull-right"), React_DOM_Props.title("Remove item"), React_DOM_Props.onClick(function (_3) {
                          return send(new RemoveItem(_16.value1));
                      }) ])([ React_DOM.text("\u2716") ]) ]);
                  };
                  var items_1 = React_DOM.table([ React_DOM_Props.className("table table-striped") ])([ React_DOM["thead'"]([ React_DOM.th([ React_DOM_Props.className("col-md-1") ])([  ]), React_DOM.th([ React_DOM_Props.className("col-md-10") ])([ React_DOM.text("Description") ]), React_DOM.th([ React_DOM_Props.className("col-md-1") ])([  ]) ]), React_DOM["tbody'"](Data_List.fromList(Data_Unfoldable.unfoldableArray)(Data_List[":"](newItem)(Prelude["<<<"](Prelude.semigroupoidFn)(Prelude.map(Data_List.functorList)(item))(Data_List.filter(Prelude["<<<"](Prelude.semigroupoidFn)(applyFilter(_10.value0.filter))(Data_Tuple.fst)))(Data_List.zip(_10.value0.items)(Data_List.range(0)(Data_List.length(_10.value0.items))))))) ]);
                  var filter__1 = function (f) {
                      return React_DOM.button([ React_DOM_Props.className((function () {
                          var _49 = Prelude["=="](eqFilter)(f)(_10.value0.filter);
                          if (_49) {
                              return "btn toolbar active";
                          };
                          if (!_49) {
                              return "btn toolbar";
                          };
                          throw new Error("Failed pattern match at Main line 120, column 1 - line 121, column 1: " + [ _49.constructor.name ]);
                      })()), React_DOM_Props.onClick(function (_4) {
                          return send(new SetFilter(f));
                      }) ])([ React_DOM.text(showFilter(f)) ]);
                  };
                  var filters = React_DOM.div([ React_DOM_Props.className("btn-group") ])(Prelude["<$>"](Prelude.functorArray)(filter__1)([ All.value, Active.value, Completed.value ]));
                  return React_DOM.div([ React_DOM_Props.className("container") ])([ title, filters, items_1 ]);
              };
          };
      };
  };
  var _State = function (__dict_Functor_10) {
      return function (f) {
          return function (_6) {
              return Prelude["<$>"](__dict_Functor_10)(State.create)(f(_6.value0));
          };
      };
  };
  var performAction = function (_13) {
      return function (action) {
          var updateState = function (_17) {
              if (_17 instanceof NewItem) {
                  return function (st) {
                      return Optic_Monad["#~"](st)(Prelude.bind(Control_Monad_State_Trans.bindStateT(Data_Identity.monadIdentity))(Optic_Monad_Setter["++="](Control_Monad_State_Trans.monadStateT(Data_Identity.monadIdentity))(Control_Monad_State_Class.monadStateStateT(Data_Identity.monadIdentity))(Data_List.semigroupList)(Optic_Core[".."](Prelude.semigroupoidFn)(_State(Data_Identity.functorIdentity))(items(Data_Identity.functorIdentity)))(Data_List.singleton(new Item(_17.value0, false))))(function () {
                          return Optic_Monad_Setter[".="](Control_Monad_State_Trans.monadStateT(Data_Identity.monadIdentity))(Control_Monad_State_Class.monadStateStateT(Data_Identity.monadIdentity))(Optic_Core[".."](Prelude.semigroupoidFn)(_State(Data_Identity.functorIdentity))(editText(Data_Identity.functorIdentity)))("");
                      }));
                  };
              };
              if (_17 instanceof RemoveItem) {
                  return Optic_Setter.over(Data_Profunctor.profunctorFn)(Optic_Core[".."](Prelude.semigroupoidFn)(_State(Data_Identity.functorIdentity))(items(Data_Identity.functorIdentity)))(function (xs) {
                      return Data_Maybe.fromMaybe(xs)(Data_List.deleteAt(_17.value0)(xs));
                  });
              };
              if (_17 instanceof SetEditText) {
                  return Optic_Setter[".~"](Optic_Core[".."](Prelude.semigroupoidFn)(_State(Data_Identity.functorIdentity))(editText(Data_Identity.functorIdentity)))(_17.value0);
              };
              if (_17 instanceof SetCompleted) {
                  return Optic_Setter[".~"](Optic_Core[".."](Prelude.semigroupoidFn)(_State(Data_Identity.functorIdentity))(Optic_Core[".."](Prelude.semigroupoidFn)(items(Data_Identity.functorIdentity))(Optic_Core[".."](Prelude.semigroupoidFn)(Optic_Index.ix(Optic_Index.indexList)(_17.value0)(Data_Identity.applicativeIdentity))(itemBoolean(Data_Identity.functorIdentity)))))(_17.value1);
              };
              if (_17 instanceof SetFilter) {
                  return Optic_Setter[".~"](Optic_Core[".."](Prelude.semigroupoidFn)(_State(Data_Identity.functorIdentity))(filter_(Data_Identity.functorIdentity)))(_17.value0);
              };
              if (_17 instanceof DoNothing) {
                  return Prelude.id(Prelude.categoryFn);
              };
              throw new Error("Failed pattern match at Main line 177, column 3 - line 178, column 3: " + [ _17.constructor.name ]);
          };
          return Thermite_Action.modifyState(updateState(action));
      };
  };
  var spec = Thermite.simpleSpec(initialState)(performAction)(render);
  var main = (function () {
      var body = function __do() {
          var _2 = DOM_HTML.window();
          var _1 = DOM_HTML_Window.document(_2)();
          var _0 = Prelude["<$>"](Control_Monad_Eff.functorEff)(Prelude["<$>"](Prelude.functorFn)(Data_Maybe_Unsafe.fromJust)(Data_Nullable.toMaybe))(DOM_HTML_Document.body(_1))();
          return Prelude["return"](Control_Monad_Eff.applicativeEff)(DOM_HTML_Types.htmlElementToElement(_0))();
      };
      var component = Thermite.createClass(spec);
      return Prelude[">>="](Control_Monad_Eff.bindEff)(body)(React.render(React.createFactory(component)({})));
  })();
  exports["main"] = main;;
 
})(PS["Main"] = PS["Main"] || {});

PS["Main"].main();
